# Based on https://github.com/Randomblock1/theos-action
name: Build Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      THEOS: /home/runner/theos
    runs-on: ubuntu-latest
    steps:

    - name: Install Deps
      shell: bash
      run: |
          sudo apt upgrade -yq && sudo apt install libplist3 libz3-4 libplist-utils -yq

    - name: Install Theos
      shell: bash
      run: |
        if [ ! -d "$THEOS" ]; then
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "Theos successfully downloaded."
          mkdir -p "$THEOS/lib/iphone/rootless"
        else
          echo "Theos already cached."
        fi

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Build packages
      run: |
        cd screendump
        make clean && make package

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: "com.julioverne.screendump_iphoneos-arm64"
        path: ${{ github.workspace }}/screendump/packages/*.deb